server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;
    location /oauth2/authorization {
        proxy_pass http://study_planner_backend:8081;
        proxy_set_header Host $host;
    }
    location /api {
        proxy_pass http://study_planner_backend:8081;
        proxy_set_header Host $host;
    }
    location /actuator {
        proxy_pass http://study_planner_backend:8081;
        proxy_set_header Host $host;
    }
    location /login/oauth2 {
        proxy_pass http://study_planner_backend:8081;
        proxy_set_header Host $host;
    }
    location / {
        try_files $uri $uri/ /index.html;
    }
}